// flow-typed signature: be2a8decfa327654bfdc5d1252274a02
// flow-typed version: <<STUB>>/prettyjson_v1.2.1/flow_v0.105.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'prettyjson'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'prettyjson' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'prettyjson/lib/prettyjson' {
  declare module.exports: any;
}

declare module 'prettyjson/lib/utils' {
  declare module.exports: any;
}

declare module 'prettyjson/test/prettyjson_spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'prettyjson/lib/prettyjson.js' {
  declare module.exports: $Exports<'prettyjson/lib/prettyjson'>;
}
declare module 'prettyjson/lib/utils.js' {
  declare module.exports: $Exports<'prettyjson/lib/utils'>;
}
declare module 'prettyjson/test/prettyjson_spec.js' {
  declare module.exports: $Exports<'prettyjson/test/prettyjson_spec'>;
}
